name: Rust Release Build

on:
  push:
      tags:
          - 'v*.*.*'

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  default: true
                  override: true

            - name: Build
              run: cargo build --release 

            - name: Run tests
              run: cargo test --verbose

            - name: Strip
              run: strip target/release/snake

            - name: Compress
              run: tar cvzf snake.tar.gz LICENSE target/release/snake

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      snake.tar.gz
                      
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

